"""Compatibility exports for the shared Nacos Prompt source implementation."""

from apps.backend.core.ai.prompt_source import (
    ImportedPromptRecord,
    NACOS_DEFAULT_VARIANT,
    NACOS_MODULE_CODE_MAP,
    NACOS_PROMPT_KEY_MAP,
    NACOS_SOURCE_TYPE,
    NACOS_XRAY_PROMPT_VARIANT_MAP,
    NacosPromptSourceClient,
    PROMPT_SOURCE_RECEIPT_V1,
    PromptSourceError,
    PromptSourceNotFoundError,
    PromptSourceUnsafeError,
    XRAY_PROMPT_VARIANTS,
    build_source_receipt,
    nacos_data_id,
    normalize_imported_prompt,
    parse_nacos_prompt_payload,
    receipt_sha256,
    variant_candidates,
)

__all__ = [
    "ImportedPromptRecord",
    "NACOS_DEFAULT_VARIANT",
    "NACOS_MODULE_CODE_MAP",
    "NACOS_PROMPT_KEY_MAP",
    "NACOS_SOURCE_TYPE",
    "NACOS_XRAY_PROMPT_VARIANT_MAP",
    "NacosPromptSourceClient",
    "PROMPT_SOURCE_RECEIPT_V1",
    "PromptSourceError",
    "PromptSourceNotFoundError",
    "PromptSourceUnsafeError",
    "XRAY_PROMPT_VARIANTS",
    "build_source_receipt",
    "nacos_data_id",
    "normalize_imported_prompt",
    "parse_nacos_prompt_payload",
    "receipt_sha256",
    "variant_candidates",
]
